version: x.x.{build}
branches:
  only:
  - master
image: Visual Studio 2015
configuration: Debug
install:
- cmd: git submodule update --init --recursive
nuget:
  disable_publish_on_pr: true
before_build:
- cmd: appveyor-retry nuget restore
build:
  project: ClashofClansPatcher.sln
  parallel: true
  verbosity: normal
artifacts:
- path: ClashofClansPatcher/bin/Debug
  name: coc_patcher_latest